//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDownloadSetting
    {
        public int AppDownloadSettingId { get; set; }
        public string KickerText { get; set; }
        public string HeadingText { get; set; }
        public string SubHeadingText { get; set; }
        public string GooglePlayUrl { get; set; }
        public string AppleAppStoreUrl { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
