//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignPollOption
    {
        public int CampaignPollOptionId { get; set; }
        public int CampaignPollId { get; set; }
        public string OptionText { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
    }
}
