//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignAlert
    {
        public int CampaignAlertId { get; set; }
        public string AlertTitle { get; set; }
        public string AlertMessage { get; set; }
        public string AlertType { get; set; }
        public string ReferenceModule { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public string Severity { get; set; }
        public string AlertStatus { get; set; }
        public string AssignedToMemberCode { get; set; }
        public string AssignedToName { get; set; }
        public string ActionTaken { get; set; }
        public string ActionTakenByMemberCode { get; set; }
        public Nullable<System.DateTime> ActionTakenDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public bool IsDashboard { get; set; }
        public bool IsNotificationSent { get; set; }
        public bool IsResolved { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public string AlertSource { get; set; }
        public bool IsRead { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public string ReadByMemberCode { get; set; }
    
        public virtual ElectionCampaign ElectionCampaign { get; set; }
    }
}
