//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignPollResponse
    {
        public int CampaignPollResponseId { get; set; }
        public int CampaignPollId { get; set; }
        public int CampaignPollOptionId { get; set; }
        public string RespondentName { get; set; }
        public string MobileNo { get; set; }
        public string AreaName { get; set; }
        public string Source { get; set; }
        public string IpAddress { get; set; }
        public string UserAgent { get; set; }
        public bool ConsentGiven { get; set; }
        public string Remarks { get; set; }
        public System.DateTime SubmittedOn { get; set; }
    }
}
