//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignMaster
    {
        public int CampaignMasterId { get; set; }
        public int ElectionId { get; set; }
        public string CampaignName { get; set; }
        public string CampaignCode { get; set; }
        public string CandidateName { get; set; }
        public string ConstituencyName { get; set; }
        public string ConstituencyNumber { get; set; }
        public string CampaignOwner { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public int ProgressPercent { get; set; }
        public string Goals { get; set; }
        public string Description { get; set; }
        public bool IsPrimary { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ElectionMaster ElectionMaster { get; set; }
    }
}
