//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitizenConnectRequest
    {
        public int CitizenConnectId { get; set; }
        public string RequestType { get; set; }
        public string FullName { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string District { get; set; }
        public string Assembly { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public string AdminRemarks { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> AssemblyConstituencyId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public Nullable<int> GramPanchayatId { get; set; }
        public Nullable<int> VillageId { get; set; }
        public string PreferredRole { get; set; }
        public string Skills { get; set; }
        public string AvailableDays { get; set; }
        public string AvailableTime { get; set; }
        public bool WhatsAppConsent { get; set; }
        public bool SmsConsent { get; set; }
        public bool EmailConsent { get; set; }
        public bool VoiceConsent { get; set; }
        public bool PrivacyConsent { get; set; }
        public Nullable<int> ConvertedPersonId { get; set; }
        public Nullable<System.DateTime> ConvertedDate { get; set; }
        public Nullable<int> ConvertedBy { get; set; }
    }
}
