//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadDocument
    {
        public int DownloadDocumentId { get; set; }
        public int DownloadCategoryId { get; set; }
        public string DocumentNumber { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string FileExtension { get; set; }
        public decimal FileSizeKB { get; set; }
        public string VersionNo { get; set; }
        public int DownloadsCount { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public bool IsFeatured { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual DownloadCategory DownloadCategory { get; set; }
    }
}
