//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectionVoter
    {
        public int VoterId { get; set; }
        public string EpicNumber { get; set; }
        public string VoterName { get; set; }
        public string FatherOrHusbandName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string MobileNumber { get; set; }
        public string Caste { get; set; }
        public string Religion { get; set; }
        public string Category { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string AssemblyConstituency { get; set; }
        public string ParliamentConstituency { get; set; }
        public string Block { get; set; }
        public string Village { get; set; }
        public string Ward { get; set; }
        public string PartNumber { get; set; }
        public string SectionNumber { get; set; }
        public string SerialNumber { get; set; }
        public string HouseNumber { get; set; }
        public string BoothNumber { get; set; }
        public string BoothName { get; set; }
        public string PollingStation { get; set; }
        public string Address { get; set; }
        public string VoterType { get; set; }
        public string PoliticalStatus { get; set; }
        public string SupportLevel { get; set; }
        public string InfluencerName { get; set; }
        public string PannaPramukhName { get; set; }
        public bool IsPriorityVoter { get; set; }
        public bool IsFirstTimeVoter { get; set; }
        public string Remarks { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string AadhaarNumber { get; set; }
        public string VoterPhotoPath { get; set; }
        public string AadhaarPhotoPath { get; set; }
    }
}
