//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElectionMaster()
        {
            this.CampaignMasters = new HashSet<CampaignMaster>();
        }
    
        public int ElectionId { get; set; }
        public string ElectionName { get; set; }
        public string ElectionType { get; set; }
        public int ElectionYear { get; set; }
        public string StateName { get; set; }
        public string DistrictName { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public Nullable<System.DateTime> NominationStartDate { get; set; }
        public Nullable<System.DateTime> NominationEndDate { get; set; }
        public Nullable<System.DateTime> PollingDate { get; set; }
        public Nullable<System.DateTime> CountingDate { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignMaster> CampaignMasters { get; set; }
    }
}
