//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectionBoothVisit
    {
        public int ElectionBoothVisitId { get; set; }
        public int ElectionBoothId { get; set; }
        public string VisitType { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string VisitorMemberCode { get; set; }
        public string VisitorName { get; set; }
        public string TeamName { get; set; }
        public int TotalTeamMembers { get; set; }
        public int HousesVisited { get; set; }
        public int FamiliesMet { get; set; }
        public int PersonsMet { get; set; }
        public int NewSupporters { get; set; }
        public int OppositionSupporters { get; set; }
        public int NeutralFamilies { get; set; }
        public int PamphletsDistributed { get; set; }
        public int MembershipFormsIssued { get; set; }
        public int MembershipFormsCollected { get; set; }
        public int PublicComplaints { get; set; }
        public bool FollowUpRequired { get; set; }
        public Nullable<System.DateTime> NextVisitDate { get; set; }
        public string VisitStatus { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string VisitSummary { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ElectionBooth ElectionBooth { get; set; }
    }
}
