//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectionLocationMaster
    {
        public int LocationId { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Block { get; set; }
        public string AssemblyConstituency { get; set; }
        public string ParliamentConstituency { get; set; }
        public string Village { get; set; }
        public string Ward { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
