//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectionBooth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElectionBooth()
        {
            this.ElectionBoothVisits = new HashSet<ElectionBoothVisit>();
            this.JanSamparks = new HashSet<JanSampark>();
        }
    
        public int ElectionBoothId { get; set; }
        public string BoothCode { get; set; }
        public string BoothNumber { get; set; }
        public string BoothName { get; set; }
        public string AssemblyName { get; set; }
        public string ParliamentName { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Block { get; set; }
        public string Village { get; set; }
        public string PollingStation { get; set; }
        public string BoothInchargeMemberCode { get; set; }
        public string BoothInchargeName { get; set; }
        public int TotalVoters { get; set; }
        public int MaleVoters { get; set; }
        public int FemaleVoters { get; set; }
        public int OtherVoters { get; set; }
        public int Supporters { get; set; }
        public int Opponents { get; set; }
        public int NeutralVoters { get; set; }
        public int VisitedHouses { get; set; }
        public int TotalHouses { get; set; }
        public decimal CoveragePercentage { get; set; }
        public string BoothStrength { get; set; }
        public Nullable<System.DateTime> LastVisitDate { get; set; }
        public Nullable<System.DateTime> LastMeetingDate { get; set; }
        public Nullable<System.DateTime> LastSurveyDate { get; set; }
        public string Priority { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectionBoothVisit> ElectionBoothVisits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JanSampark> JanSamparks { get; set; }
    }
}
