//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventAttendance
    {
        public int AttendanceId { get; set; }
        public int EventId { get; set; }
        public string AttendanceType { get; set; }
        public string PersonName { get; set; }
        public string FatherName { get; set; }
        public string MobileNumber { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Block { get; set; }
        public string Village { get; set; }
        public string Booth { get; set; }
        public string WorkerName { get; set; }
        public string WorkerCode { get; set; }
        public string MemberCode { get; set; }
        public string AttendanceMode { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public bool IsVIP { get; set; }
        public bool IsVolunteer { get; set; }
        public bool IsWorker { get; set; }
        public bool IsVerified { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual EventMaster EventMaster { get; set; }
    }
}
