//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventPublicProfile
    {
        public int EventId { get; set; }
        public string SubTitle { get; set; }
        public string EventScope { get; set; }
        public bool ShowOnHome { get; set; }
        public bool ShowInElectionWarRoom { get; set; }
        public bool IsConfidential { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string FullAddress { get; set; }
        public string GoogleMapLink { get; set; }
        public string EventImagePath { get; set; }
        public int ExpectedVehicles { get; set; }
        public int ActualVehicles { get; set; }
        public int ExpectedVolunteers { get; set; }
        public int ActualVolunteers { get; set; }
        public int ExpectedFoodPlates { get; set; }
        public int ActualFoodPlates { get; set; }
        public string ResponsiblePerson { get; set; }
        public string ResponsibleMobile { get; set; }
        public string TransportResponsible { get; set; }
        public string FoodResponsible { get; set; }
        public string MediaResponsible { get; set; }
        public string VolunteerResponsible { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
