//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTaskActivity
    {
        public int EventTaskActivityId { get; set; }
        public int EventTaskId { get; set; }
        public string ActivityType { get; set; }
        public string OldStatus { get; set; }
        public string NewStatus { get; set; }
        public Nullable<int> ProgressPercentage { get; set; }
        public string ActivityRemarks { get; set; }
        public string AttachmentPath { get; set; }
        public string ActivityByMemberCode { get; set; }
        public string ActivityByName { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EventTask EventTask { get; set; }
    }
}
