//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventTeam()
        {
            this.EventTasks = new HashSet<EventTask>();
            this.EventTeamMembers = new HashSet<EventTeamMember>();
        }
    
        public int EventTeamId { get; set; }
        public int EventId { get; set; }
        public string TeamName { get; set; }
        public string TeamLeaderName { get; set; }
        public string TeamLeaderMobile { get; set; }
        public int TotalMembers { get; set; }
        public int RequiredMembers { get; set; }
        public string AssignedArea { get; set; }
        public Nullable<System.DateTime> DutyStartTime { get; set; }
        public Nullable<System.DateTime> DutyEndTime { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public string Instructions { get; set; }
        public string Remarks { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EventMaster EventMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTask> EventTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTeamMember> EventTeamMembers { get; set; }
    }
}
