//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventExpense
    {
        public int EventExpenseId { get; set; }
        public int EventId { get; set; }
        public string ExpenseCategory { get; set; }
        public string ExpenseHead { get; set; }
        public string VendorName { get; set; }
        public string VendorMobile { get; set; }
        public string BillNumber { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Unit { get; set; }
        public decimal Rate { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentStatus { get; set; }
        public string PaidTo { get; set; }
        public string PaidBy { get; set; }
        public string TransactionReference { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public string ApprovedBy { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ExpenseStatus { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
    
        public virtual EventMaster EventMaster { get; set; }
    }
}
