//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventPollResponse
    {
        public int EventPollResponseId { get; set; }
        public int EventPollId { get; set; }
        public Nullable<int> EventPollOptionId { get; set; }
        public string SurveyPersonMemberCode { get; set; }
        public string SurveyPersonName { get; set; }
        public string RespondentName { get; set; }
        public string RespondentMobile { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Block { get; set; }
        public string Village { get; set; }
        public string Booth { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string ResponseText { get; set; }
        public string DeviceId { get; set; }
        public bool IsVerified { get; set; }
        public System.DateTime ResponseDate { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EventPoll EventPoll { get; set; }
        public virtual EventPollOption EventPollOption { get; set; }
    }
}
