//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventVehicle
    {
        public int EventVehicleId { get; set; }
        public int EventId { get; set; }
        public string VillageName { get; set; }
        public string BoothName { get; set; }
        public string WorkerName { get; set; }
        public string WorkerMobile { get; set; }
        public string Responsibility { get; set; }
        public string VehicleType { get; set; }
        public int VehicleCount { get; set; }
        public int EstimatedPersons { get; set; }
        public int ActualPersons { get; set; }
        public string DriverName { get; set; }
        public string DriverMobile { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public string ParkingZone { get; set; }
        public decimal FuelExpense { get; set; }
        public string Remarks { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string WorkerCode { get; set; }
    
        public virtual EventMaster EventMaster { get; set; }
    }
}
