//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTrackingItem
    {
        public int EventTrackingItemId { get; set; }
        public int EventId { get; set; }
        public string Category { get; set; }
        public string ItemName { get; set; }
        public string Village { get; set; }
        public string Ward { get; set; }
        public string Booth { get; set; }
        public string ResponsiblePerson { get; set; }
        public string ResponsibleMobile { get; set; }
        public int ExpectedQuantity { get; set; }
        public int ActualQuantity { get; set; }
        public string Unit { get; set; }
        public decimal EstimatedCost { get; set; }
        public decimal ActualCost { get; set; }
        public string ProviderName { get; set; }
        public string ProviderMobile { get; set; }
        public bool ReturnRequired { get; set; }
        public bool Returned { get; set; }
        public bool AppreciationPending { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
