//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTeamMember
    {
        public int EventTeamMemberId { get; set; }
        public int EventTeamId { get; set; }
        public string MemberName { get; set; }
        public string MemberCode { get; set; }
        public string MobileNumber { get; set; }
        public string Designation { get; set; }
        public string Responsibility { get; set; }
        public string AttendanceStatus { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public bool IsLeader { get; set; }
        public bool IsPresent { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ReportingMemberCode { get; set; }
    
        public virtual EventTeam EventTeam { get; set; }
    }
}
