//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventGuest
    {
        public int EventGuestId { get; set; }
        public int EventId { get; set; }
        public string GuestName { get; set; }
        public string Designation { get; set; }
        public string Organization { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string GuestCategory { get; set; }
        public string InvitationStatus { get; set; }
        public string ConfirmationStatus { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public bool VehicleRequired { get; set; }
        public string VehicleDetails { get; set; }
        public string DriverName { get; set; }
        public string DriverMobile { get; set; }
        public bool HotelRequired { get; set; }
        public string HotelName { get; set; }
        public string RoomNumber { get; set; }
        public bool SecurityRequired { get; set; }
        public string SecurityLevel { get; set; }
        public string StageSeatNumber { get; set; }
        public string ProtocolOfficer { get; set; }
        public string EscortOfficer { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EventMaster EventMaster { get; set; }
    }
}
