//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventTask()
        {
            this.EventTask1 = new HashSet<EventTask>();
            this.EventTaskActivities = new HashSet<EventTaskActivity>();
        }
    
        public int EventTaskId { get; set; }
        public int EventId { get; set; }
        public Nullable<int> ParentTaskId { get; set; }
        public string TaskTitle { get; set; }
        public string TaskDescription { get; set; }
        public string TaskCategory { get; set; }
        public string AssignedToMemberCode { get; set; }
        public string AssignedToName { get; set; }
        public Nullable<int> AssignedTeamId { get; set; }
        public string AssignedByMemberCode { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public int ProgressPercentage { get; set; }
        public Nullable<decimal> EstimatedHours { get; set; }
        public Nullable<decimal> ActualHours { get; set; }
        public bool IsMilestone { get; set; }
        public bool RequiresApproval { get; set; }
        public string ApprovedByMemberCode { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EventMaster EventMaster { get; set; }
        public virtual EventTeam EventTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTask> EventTask1 { get; set; }
        public virtual EventTask EventTask2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTaskActivity> EventTaskActivities { get; set; }
    }
}
