//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeographyImportHistory
    {
        public int ImportHistoryId { get; set; }
        public string EntityType { get; set; }
        public string SourceName { get; set; }
        public string FileName { get; set; }
        public int InsertedCount { get; set; }
        public int UpdatedCount { get; set; }
        public int ErrorCount { get; set; }
        public Nullable<int> ImportedBy { get; set; }
        public System.DateTime ImportedDate { get; set; }
        public Nullable<int> StateId { get; set; }
        public int TotalRows { get; set; }
        public int InsertedRows { get; set; }
        public int UpdatedRows { get; set; }
        public int SkippedRows { get; set; }
        public int FailedRows { get; set; }
    }
}
