//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeroSlider
    {
        public int HeroSliderId { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public string ButtonText { get; set; }
        public string ButtonUrl { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string ButtonText2 { get; set; }
        public string ButtonUrl2 { get; set; }
        public string MobileImagePath { get; set; }
        public string TemplateType { get; set; }
        public string OverlayType { get; set; }
        public string SliderTransition { get; set; }
        public string TitleAnimation { get; set; }
        public string SubTitleAnimation { get; set; }
        public string DescriptionAnimation { get; set; }
        public string ButtonAnimation { get; set; }
        public string TextAlignment { get; set; }
        public Nullable<decimal> OverlayOpacity { get; set; }
        public string BackgroundImagePath { get; set; }
        public string LeaderImagePath { get; set; }
        public string BackgroundColor { get; set; }
        public string LeaderImagePosition { get; set; }
        public bool ShowLeaderImage { get; set; }
        public bool ShowOverlay { get; set; }
        public bool ShowButtons { get; set; }
        public bool IsVideoSlide { get; set; }
        public string VideoSourceType { get; set; }
        public string VideoUrl { get; set; }
        public string VideoPath { get; set; }
        public bool VideoAutoplay { get; set; }
        public bool VideoMuted { get; set; }
        public bool VideoLoop { get; set; }
        public string HeroHeightCss { get; set; }
    }
}
