//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePageSection
    {
        public int HomePageSectionId { get; set; }
        public string SectionKey { get; set; }
        public string SectionName { get; set; }
        public string Description { get; set; }
        public string RenderType { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string PartialViewPath { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsVisible { get; set; }
        public bool IsSystem { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
