//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JanSampark
    {
        public int JanSamparkId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> ElectionBoothId { get; set; }
        public string CitizenName { get; set; }
        public string FatherName { get; set; }
        public string MobileNumber { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Block { get; set; }
        public string Village { get; set; }
        public string Booth { get; set; }
        public string Address { get; set; }
        public string Category { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public string AssignedToMemberCode { get; set; }
        public string AssignedToName { get; set; }
        public string Resolution { get; set; }
        public Nullable<System.DateTime> ResolutionDate { get; set; }
        public bool FollowUpRequired { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string AttachmentPath { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public bool IsResolved { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ElectionBooth ElectionBooth { get; set; }
        public virtual EventMaster EventMaster { get; set; }
    }
}
