//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaderIntroduction
    {
        public int LeaderIntroductionId { get; set; }
        public string LeaderName { get; set; }
        public string RoleTagline { get; set; }
        public string SectionLabel { get; set; }
        public string IntroText { get; set; }
        public string SecondaryText { get; set; }
        public string VisionTitle { get; set; }
        public string VisionText { get; set; }
        public string MissionTitle { get; set; }
        public string MissionText { get; set; }
        public string PortraitImagePath { get; set; }
        public string StatusTitle { get; set; }
        public string StatusText { get; set; }
        public string PrimaryButtonText { get; set; }
        public string PrimaryButtonUrl { get; set; }
        public string SecondaryButtonText { get; set; }
        public string SecondaryButtonUrl { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
