//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuMaster()
        {
            this.MenuMaster1 = new HashSet<MenuMaster>();
        }
    
        public int MenuId { get; set; }
        public Nullable<int> ParentMenuId { get; set; }
        public string MenuName { get; set; }
        public string MenuDescription { get; set; }
        public string AreaName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string RouteValues { get; set; }
        public string CustomUrl { get; set; }
        public string MenuType { get; set; }
        public string IconClass { get; set; }
        public string CssClass { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public bool ShowOnHome { get; set; }
        public bool ShowInAdminSidebar { get; set; }
        public bool OpenInNewTab { get; set; }
        public bool IsClickable { get; set; }
        public bool HasMegaMenu { get; set; }
        public string PageTitle { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int MenuLevel { get; set; }
        public bool ShowInFooter { get; set; }
        public bool ShowInQuickLinks { get; set; }
        public bool IsSystemMenu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuMaster> MenuMaster1 { get; set; }
        public virtual MenuMaster MenuMaster2 { get; set; }
    }
}
