//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuCondition
    {
        public int MenuConditionId { get; set; }
        public int MenuId { get; set; }
        public string MenuLocation { get; set; }
        public bool RequireLogin { get; set; }
        public string RequiredRole { get; set; }
        public string RequiredPermissionKey { get; set; }
        public bool RequireCampaignContext { get; set; }
        public string FeatureKey { get; set; }
        public Nullable<System.DateTime> VisibleFrom { get; set; }
        public Nullable<System.DateTime> VisibleUntil { get; set; }
        public bool ShowOnDesktop { get; set; }
        public bool ShowOnMobile { get; set; }
        public string LanguageCode { get; set; }
        public string BadgeKey { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual MenuMaster MenuMaster { get; set; }
    }
}
