//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavigationMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NavigationMenu()
        {
            this.NavigationMenu1 = new HashSet<NavigationMenu>();
        }
    
        public int NavigationMenuId { get; set; }
        public Nullable<int> ParentMenuId { get; set; }
        public string MenuTitle { get; set; }
        public string MenuUrl { get; set; }
        public string MenuIcon { get; set; }
        public int DisplayOrder { get; set; }
        public bool OpenInNewTab { get; set; }
        public bool IsVisible { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NavigationMenu> NavigationMenu1 { get; set; }
        public virtual NavigationMenu NavigationMenu2 { get; set; }
    }
}
