//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonRoleAssignment
    {
        public int PersonRoleAssignmentId { get; set; }
        public int PersonId { get; set; }
        public string RoleCode { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> AssemblyConstituencyId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public Nullable<int> GramPanchayatId { get; set; }
        public Nullable<int> VillageId { get; set; }
        public Nullable<int> WardId { get; set; }
        public Nullable<int> MandalId { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> BoothId { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public bool IsPrimary { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual PersonMaster PersonMaster { get; set; }
    }
}
