//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonMaster()
        {
            this.PersonRoleAssignments = new HashSet<PersonRoleAssignment>();
            this.VolunteerProfiles = new HashSet<VolunteerProfile>();
        }
    
        public int PersonId { get; set; }
        public string FullName { get; set; }
        public string MobileNumber { get; set; }
        public string NormalizedMobile { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string AddressLine { get; set; }
        public string Landmark { get; set; }
        public string PinCode { get; set; }
        public string PreferredLanguage { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> ParliamentaryConstituencyId { get; set; }
        public Nullable<int> AssemblyConstituencyId { get; set; }
        public Nullable<int> TehsilId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public Nullable<int> GramPanchayatId { get; set; }
        public Nullable<int> VillageId { get; set; }
        public Nullable<int> WardId { get; set; }
        public Nullable<int> MandalId { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> BoothId { get; set; }
        public bool WhatsAppConsent { get; set; }
        public bool SmsConsent { get; set; }
        public bool EmailConsent { get; set; }
        public bool VoiceCallConsent { get; set; }
        public Nullable<System.DateTime> ConsentDate { get; set; }
        public string ConsentSource { get; set; }
        public bool IsOptedOut { get; set; }
        public Nullable<System.DateTime> OptOutDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonRoleAssignment> PersonRoleAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VolunteerProfile> VolunteerProfiles { get; set; }
    }
}
