//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoliticalLeaderPortalDbEntities1 : DbContext
    {
        public PoliticalLeaderPortalDbEntities1()
            : base("name=PoliticalLeaderPortalDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationRole> ApplicationRoles { get; set; }
        public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public virtual DbSet<HeroSlider> HeroSliders { get; set; }
        public virtual DbSet<HomePageStatistic> HomePageStatistics { get; set; }
        public virtual DbSet<NavigationMenu> NavigationMenus { get; set; }
        public virtual DbSet<WebsiteFooterSetting> WebsiteFooterSettings { get; set; }
        public virtual DbSet<WebsiteHeaderSetting> WebsiteHeaderSettings { get; set; }
        public virtual DbSet<WebsiteSetting> WebsiteSettings { get; set; }
        public virtual DbSet<LatestNew> LatestNews { get; set; }
        public virtual DbSet<UpcomingEvent> UpcomingEvents { get; set; }
        public virtual DbSet<GalleryCategory> GalleryCategories { get; set; }
        public virtual DbSet<GalleryImage> GalleryImages { get; set; }
        public virtual DbSet<VideoCategory> VideoCategories { get; set; }
        public virtual DbSet<VideoGallery> VideoGalleries { get; set; }
        public virtual DbSet<MediaCoverage> MediaCoverages { get; set; }
        public virtual DbSet<DownloadCategory> DownloadCategories { get; set; }
        public virtual DbSet<DownloadDocument> DownloadDocuments { get; set; }
        public virtual DbSet<CampaignAlert> CampaignAlerts { get; set; }
        public virtual DbSet<ElectionBooth> ElectionBooths { get; set; }
        public virtual DbSet<ElectionBoothVisit> ElectionBoothVisits { get; set; }
        public virtual DbSet<ElectionCampaign> ElectionCampaigns { get; set; }
        public virtual DbSet<EventArrangement> EventArrangements { get; set; }
        public virtual DbSet<EventAttendance> EventAttendances { get; set; }
        public virtual DbSet<EventExpense> EventExpenses { get; set; }
        public virtual DbSet<EventGuest> EventGuests { get; set; }
        public virtual DbSet<EventMaster> EventMasters { get; set; }
        public virtual DbSet<EventMedia> EventMedias { get; set; }
        public virtual DbSet<EventPoll> EventPolls { get; set; }
        public virtual DbSet<EventPollOption> EventPollOptions { get; set; }
        public virtual DbSet<EventPollResponse> EventPollResponses { get; set; }
        public virtual DbSet<EventTask> EventTasks { get; set; }
        public virtual DbSet<EventTaskActivity> EventTaskActivities { get; set; }
        public virtual DbSet<EventTeam> EventTeams { get; set; }
        public virtual DbSet<EventTeamMember> EventTeamMembers { get; set; }
        public virtual DbSet<EventVehicle> EventVehicles { get; set; }
        public virtual DbSet<JanSampark> JanSamparks { get; set; }
        public virtual DbSet<MenuMaster> MenuMasters { get; set; }
    }
}
