//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoliticalLeaderPortalDbEntities1 : DbContext
    {
        public PoliticalLeaderPortalDbEntities1()
            : base("name=PoliticalLeaderPortalDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationRole> ApplicationRoles { get; set; }
        public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public virtual DbSet<HeroSlider> HeroSliders { get; set; }
        public virtual DbSet<HomePageStatistic> HomePageStatistics { get; set; }
        public virtual DbSet<NavigationMenu> NavigationMenus { get; set; }
        public virtual DbSet<WebsiteFooterSetting> WebsiteFooterSettings { get; set; }
        public virtual DbSet<WebsiteHeaderSetting> WebsiteHeaderSettings { get; set; }
        public virtual DbSet<WebsiteSetting> WebsiteSettings { get; set; }
        public virtual DbSet<LatestNew> LatestNews { get; set; }
        public virtual DbSet<UpcomingEvent> UpcomingEvents { get; set; }
        public virtual DbSet<GalleryCategory> GalleryCategories { get; set; }
        public virtual DbSet<GalleryImage> GalleryImages { get; set; }
        public virtual DbSet<VideoCategory> VideoCategories { get; set; }
        public virtual DbSet<VideoGallery> VideoGalleries { get; set; }
        public virtual DbSet<MediaCoverage> MediaCoverages { get; set; }
        public virtual DbSet<DownloadCategory> DownloadCategories { get; set; }
        public virtual DbSet<DownloadDocument> DownloadDocuments { get; set; }
        public virtual DbSet<CampaignAlert> CampaignAlerts { get; set; }
        public virtual DbSet<ElectionBooth> ElectionBooths { get; set; }
        public virtual DbSet<ElectionBoothVisit> ElectionBoothVisits { get; set; }
        public virtual DbSet<ElectionCampaign> ElectionCampaigns { get; set; }
        public virtual DbSet<EventArrangement> EventArrangements { get; set; }
        public virtual DbSet<EventAttendance> EventAttendances { get; set; }
        public virtual DbSet<EventExpense> EventExpenses { get; set; }
        public virtual DbSet<EventGuest> EventGuests { get; set; }
        public virtual DbSet<EventMaster> EventMasters { get; set; }
        public virtual DbSet<EventMedia> EventMedias { get; set; }
        public virtual DbSet<EventPoll> EventPolls { get; set; }
        public virtual DbSet<EventPollOption> EventPollOptions { get; set; }
        public virtual DbSet<EventPollResponse> EventPollResponses { get; set; }
        public virtual DbSet<EventTask> EventTasks { get; set; }
        public virtual DbSet<EventTaskActivity> EventTaskActivities { get; set; }
        public virtual DbSet<EventTeam> EventTeams { get; set; }
        public virtual DbSet<EventTeamMember> EventTeamMembers { get; set; }
        public virtual DbSet<EventVehicle> EventVehicles { get; set; }
        public virtual DbSet<JanSampark> JanSamparks { get; set; }
        public virtual DbSet<MenuMaster> MenuMasters { get; set; }
        public virtual DbSet<AppDownloadSetting> AppDownloadSettings { get; set; }
        public virtual DbSet<CampaignPoll> CampaignPolls { get; set; }
        public virtual DbSet<CampaignPollOption> CampaignPollOptions { get; set; }
        public virtual DbSet<CampaignPollResponse> CampaignPollResponses { get; set; }
        public virtual DbSet<CitizenConnectRequest> CitizenConnectRequests { get; set; }
        public virtual DbSet<ElectionLocationMaster> ElectionLocationMasters { get; set; }
        public virtual DbSet<ElectionVoter> ElectionVoters { get; set; }
        public virtual DbSet<EventPublicProfile> EventPublicProfiles { get; set; }
        public virtual DbSet<EventTrackingItem> EventTrackingItems { get; set; }
        public virtual DbSet<HomeMember> HomeMembers { get; set; }
        public virtual DbSet<HomePageSection> HomePageSections { get; set; }
        public virtual DbSet<LeaderIntroduction> LeaderIntroductions { get; set; }
        public virtual DbSet<MenuCondition> MenuConditions { get; set; }
        public virtual DbSet<MeraKshetraItem> MeraKshetraItems { get; set; }
        public virtual DbSet<PublicNewsTicker> PublicNewsTickers { get; set; }
        public virtual DbSet<RoleMenuPermission> RoleMenuPermissions { get; set; }
        public virtual DbSet<SiteHitCounter> SiteHitCounters { get; set; }
        public virtual DbSet<TodaySchedule> TodaySchedules { get; set; }
        public virtual DbSet<VoterBackupSetting> VoterBackupSettings { get; set; }
        public virtual DbSet<CampaignMaster> CampaignMasters { get; set; }
        public virtual DbSet<ElectionMaster> ElectionMasters { get; set; }
        public virtual DbSet<AssemblyConstituencyMaster> AssemblyConstituencyMasters { get; set; }
        public virtual DbSet<BlockMaster> BlockMasters { get; set; }
        public virtual DbSet<DistrictMaster> DistrictMasters { get; set; }
        public virtual DbSet<GeographyImportHistory> GeographyImportHistories { get; set; }
        public virtual DbSet<GramPanchayatMaster> GramPanchayatMasters { get; set; }
        public virtual DbSet<ParliamentaryConstituencyMaster> ParliamentaryConstituencyMasters { get; set; }
        public virtual DbSet<StateMaster> StateMasters { get; set; }
        public virtual DbSet<TehsilMaster> TehsilMasters { get; set; }
        public virtual DbSet<VillageMaster> VillageMasters { get; set; }
        public virtual DbSet<WardMaster> WardMasters { get; set; }
        public virtual DbSet<PersonMaster> PersonMasters { get; set; }
        public virtual DbSet<PersonRoleAssignment> PersonRoleAssignments { get; set; }
        public virtual DbSet<VolunteerProfile> VolunteerProfiles { get; set; }
    }
}
