//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteHitCounter
    {
        public string CounterKey { get; set; }
        public int HitCount { get; set; }
        public Nullable<System.DateTime> LastHitOn { get; set; }
    }
}
