//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StateMaster()
        {
            this.AssemblyConstituencyMasters = new HashSet<AssemblyConstituencyMaster>();
            this.BlockMasters = new HashSet<BlockMaster>();
            this.DistrictMasters = new HashSet<DistrictMaster>();
            this.GramPanchayatMasters = new HashSet<GramPanchayatMaster>();
            this.ParliamentaryConstituencyMasters = new HashSet<ParliamentaryConstituencyMaster>();
            this.TehsilMasters = new HashSet<TehsilMaster>();
            this.VillageMasters = new HashSet<VillageMaster>();
            this.WardMasters = new HashSet<WardMaster>();
        }
    
        public int StateId { get; set; }
        public string Code { get; set; }
        public string NameEnglish { get; set; }
        public string NameHindi { get; set; }
        public bool IsUnionTerritory { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string SourceName { get; set; }
        public Nullable<System.DateTime> SourceUpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemblyConstituencyMaster> AssemblyConstituencyMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockMaster> BlockMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistrictMaster> DistrictMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GramPanchayatMaster> GramPanchayatMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParliamentaryConstituencyMaster> ParliamentaryConstituencyMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TehsilMaster> TehsilMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VillageMaster> VillageMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WardMaster> WardMasters { get; set; }
    }
}
