//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoGallery
    {
        public int VideoId { get; set; }
        public int VideoCategoryId { get; set; }
        public string VideoTitle { get; set; }
        public string VideoDescription { get; set; }
        public string YoutubeUrl { get; set; }
        public string ThumbnailImagePath { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsFeatured { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual VideoCategory VideoCategory { get; set; }
    }
}
