//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VillageMaster
    {
        public int VillageId { get; set; }
        public int StateId { get; set; }
        public int DistrictId { get; set; }
        public Nullable<int> TehsilId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public Nullable<int> GramPanchayatId { get; set; }
        public string Code { get; set; }
        public string NameEnglish { get; set; }
        public string NameHindi { get; set; }
        public string AreaType { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> LGDVersion { get; set; }
        public string VillageCategory { get; set; }
        public string VillageStatus { get; set; }
        public string Census2001Code { get; set; }
        public string Census2011Code { get; set; }
        public string Remark { get; set; }
        public string SourceName { get; set; }
    
        public virtual BlockMaster BlockMaster { get; set; }
        public virtual DistrictMaster DistrictMaster { get; set; }
        public virtual GramPanchayatMaster GramPanchayatMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        public virtual TehsilMaster TehsilMaster { get; set; }
    }
}
