//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteerProfile
    {
        public int VolunteerProfileId { get; set; }
        public int PersonId { get; set; }
        public string PreferredRole { get; set; }
        public string Skills { get; set; }
        public string AvailableDays { get; set; }
        public string AvailableTime { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactMobile { get; set; }
        public string Status { get; set; }
        public string VerificationStatus { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Notes { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual PersonMaster PersonMaster { get; set; }
    }
}
