//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoterBackupSetting
    {
        public int BackupSettingId { get; set; }
        public bool AutoBackupEnabled { get; set; }
        public int KeepLatestFiles { get; set; }
        public bool MirrorToDriveFolder { get; set; }
        public string DriveMirrorFolderPath { get; set; }
        public string LastBackupFilePath { get; set; }
        public string LastMirrorFilePath { get; set; }
        public string LastBackupStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
