//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WardMaster
    {
        public int WardId { get; set; }
        public int StateId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> AssemblyConstituencyId { get; set; }
        public string Code { get; set; }
        public string NameEnglish { get; set; }
        public string NameHindi { get; set; }
        public string AreaType { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual AssemblyConstituencyMaster AssemblyConstituencyMaster { get; set; }
        public virtual DistrictMaster DistrictMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
    }
}
