//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteHeaderSetting
    {
        public int WebsiteHeaderSettingId { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public string FacebookUrl { get; set; }
        public string InstagramUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string YoutubeUrl { get; set; }
        public string WhatsappUrl { get; set; }
        public bool ShowTopBar { get; set; }
        public bool ShowLanguageSwitcher { get; set; }
        public bool ShowSignIn { get; set; }
        public bool ShowSignUp { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string LogoPath { get; set; }
        public string LeaderImagePath { get; set; }
        public string HeaderBackgroundColor { get; set; }
        public string HeaderTextColor { get; set; }
        public string HeaderFontFamily { get; set; }
        public string HeaderFontSize { get; set; }
        public string LogoAnimationClass { get; set; }
        public string TextAnimationClass { get; set; }
    }
}
