//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalLeaderPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteSetting
    {
        public int WebsiteSettingId { get; set; }
        public string WebsiteName { get; set; }
        public string WebsiteTagline { get; set; }
        public string WebsiteLogoPath { get; set; }
        public string FaviconPath { get; set; }
        public string DefaultMetaTitle { get; set; }
        public string DefaultMetaDescription { get; set; }
        public string DefaultMetaKeywords { get; set; }
        public string GoogleAnalyticsCode { get; set; }
        public string GoogleSearchConsoleCode { get; set; }
        public string DefaultLanguage { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
