SET NOCOUNT ON;
IF OBJECT_ID('dbo.VoiceAgentSetting','U') IS NULL
CREATE TABLE dbo.VoiceAgentSetting(VoiceAgentSettingId INT IDENTITY PRIMARY KEY,ProviderName NVARCHAR(50) NOT NULL,
AccountSid NVARCHAR(1000) NULL,AuthToken NVARCHAR(2000) NULL,PhoneNumber NVARCHAR(30) NULL,WebhookSecret NVARCHAR(100) NOT NULL,
PublicBaseUrl NVARCHAR(300) NULL,IsEnabled BIT NOT NULL DEFAULT(0),EnableRecording BIT NOT NULL DEFAULT(1),
RecordingConsentText NVARCHAR(500) NOT NULL,WelcomeMessageHindi NVARCHAR(500) NOT NULL,WelcomeMessageEnglish NVARCHAR(500) NOT NULL,
AiApiEndpoint NVARCHAR(300) NULL,AiApiKey NVARCHAR(2000) NULL,RecordingRetentionDays INT NOT NULL DEFAULT(90),
CreatedBy INT NULL,CreatedDate DATETIME NOT NULL DEFAULT(GETDATE()),ModifiedBy INT NULL,ModifiedDate DATETIME NULL);
IF OBJECT_ID('dbo.VoiceCallLog','U') IS NULL
BEGIN
CREATE TABLE dbo.VoiceCallLog(VoiceCallId BIGINT IDENTITY PRIMARY KEY,ProviderCallId NVARCHAR(150) NOT NULL,Direction NVARCHAR(20) NOT NULL,
CallerNumber NVARCHAR(40) NULL,CalledNumber NVARCHAR(40) NULL,Status NVARCHAR(30) NOT NULL,StartedAt DATETIME NOT NULL,
AnsweredAt DATETIME NULL,EndedAt DATETIME NULL,DurationSeconds INT NOT NULL DEFAULT(0),Language NVARCHAR(20) NULL,Intent NVARCHAR(120) NULL,
Transcript NVARCHAR(MAX) NULL,Summary NVARCHAR(2000) NULL,RecordingUrl NVARCHAR(1000) NULL,LocalRecordingPath NVARCHAR(500) NULL,
RecordingDurationSeconds INT NOT NULL DEFAULT(0),RecordingConsentGiven BIT NOT NULL DEFAULT(0),CreatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
ModifiedDate DATETIME NULL);
CREATE UNIQUE INDEX UX_VoiceCallLog_ProviderCallId ON dbo.VoiceCallLog(ProviderCallId);
END;
